spring:
  data:
    mongodb:
      uri: mongodb+srv://mukeshyadavbt01:DVAjiEiE8oGF74hd@cluster0.xx3j9.mongodb.net/journalDB?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
management:
  endpoints:
    web:
      exposure:
        include: "*"  # If you want all endpoints exposed, otherwise list specific ones
    health:
      show-details: always  # This will always show the details for health endpoints

server:
  port: 8182
  servlet:
    context-path: /journal  # Adjust this if necessary

#Enabled logging level from DEBUG  to its above level severity
#logging:
#  level:
#    com:
#      springbootmongo: DEBUG

#If we want to close all logging level from root then we can do like this

#logging:
#  level:
#    root: OFF

