spring:
  data:
    mongodb:
      uri: mongodb+srv://mukeshyadavbt01:DVAjiEiE8oGF74hd@cluster0.xx3j9.mongodb.net/journalDB?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: mukeshyadavbt01@gmail.com
    password: fvchjhukyskjytwj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

server:
  port: 8182
  servlet:
    context-path: /journal

weather:
  api:
    key: 822f8cfdb03a4358040c24fd9c77f12f

# Optional logging setup
# logging:
#   level:
#     com:
#       springbootmongo: DEBUG
